<a href="https://colab.research.google.com/github/ASIMULCAY/Clarusway/blob/master/Assignment_1_ASIM_ULCAY(2).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

___

<p style="text-align: center;"><img src="https://docs.google.com/uc?id=1lY0Uj5R04yMY3-ZppPWxqCr5pvBLYPnV" class="img-fluid" 
alt="CLRSWY"></p>

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#9d4f8c; font-size:100%; text-align:center; border-radius:10px 10px;">WAY TO REINVENT YOURSELF</p>

___

In this assignment you will start off with Numpy Exercises and then complete the whole Exercise with Pandas questions. All the subjects related to questions here already covered in preclass materials and in-class sessions. So good luck!


#### 1. Import NumPy Library

In [1]:
import numpy as np

#### 2. Create an array from my_list=[5,10,15,20,25]

In [2]:
my_list=[5,10,15,20,25]

In [3]:
my_array=np.array(my_list)
my_array

array([ 5, 10, 15, 20, 25])

#### 3. Generate an array of 5x5 with zeros 

In [4]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

#### 4. Generate an array of 4x4 with ones and assign data type as int

In [5]:
np.ones((4,4), dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

#### 5. Make all the values of the array above 7

In [6]:
arr = np.ones((4,4),dtype=int)*7
arr

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

#### 6. Create thr previous array above by full() method

In [7]:
np.full((4,4),7)

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

#### 7. Create an array of even integers from 2 to 16 (inclusive) 

In [8]:
np.arange(2,17,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16])

#### 8. Create a 5x5 matrix with the values between 0 to 25 (exclusive)

In [9]:
np.arange(0,25).reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [10]:
np.arange(0,25).reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

#### 9. Create a 5x5 matrix with the values between 0 to 25 (exclusive) using linspace

In [11]:
np.arange(25).reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [12]:
np.linspace(0,24,num=25,dtype=int).reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

#### 10. Create randomly 5 numbers with numpy

In [13]:
np.random.rand(5)

array([0.2407953 , 0.07920192, 0.33710976, 0.94414001, 0.60569705])

#### 11. Create an array of 5*5 shape and fills it with random values as per the standard normal distribution

In [14]:
np.random.randn(5,5)

array([[-9.06651049e-01,  8.79004441e-01, -9.37177242e-01,
         1.68532760e+00,  3.29343987e-01],
       [ 3.85268387e-01,  1.41064393e+00,  1.63155453e-04,
         3.91850624e-01,  1.43749142e-01],
       [ 8.59160543e-01, -1.35029752e+00, -2.74873692e-01,
         1.24450800e+00,  4.23588728e-01],
       [-8.33233260e-01, -5.92777972e-01,  1.23818612e+00,
         8.86540601e-01,  7.96173728e-01],
       [-7.07792775e-02, -1.56700596e+00, -1.21546175e+00,
         4.12996301e-01, -9.50398969e-01]])

#### 12. Create a 3*4 array of random int numbers between 20 and 50

In [15]:
np.random.randint(20,50,size=(3,4))

array([[38, 39, 33, 47],
       [22, 48, 29, 34],
       [41, 30, 29, 33]])

#### 13. Reshape the array below with the shape of 6x8

In [16]:
ranarr= np.random.randint(0,50,size=(6,8))

In [17]:
ranarr

array([[37, 46, 12, 46,  5, 40, 23,  4],
       [21, 36, 16,  3, 35, 46, 27,  4],
       [19, 39, 29, 13, 35, 41, 29, 43],
       [14, 10, 31, 37, 13,  5, 37, 25],
       [14, 34,  3, 15, 27, 49, 25, 20],
       [19, 10, 31, 31, 18, 23,  1, 32]])

In [18]:
#reshape with -1
ranarr.reshape(4,-1)

array([[37, 46, 12, 46,  5, 40, 23,  4, 21, 36, 16,  3],
       [35, 46, 27,  4, 19, 39, 29, 13, 35, 41, 29, 43],
       [14, 10, 31, 37, 13,  5, 37, 25, 14, 34,  3, 15],
       [27, 49, 25, 20, 19, 10, 31, 31, 18, 23,  1, 32]])

## Numpy Indexing and Selection


In [19]:
#Create array below
mat=np.arange(1,17).reshape(4,4)
mat

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

#### 14. Using the array above, write a code that reproduces the output shown below.<br>

In [20]:
mat[1:3,1:3]

array([[ 6,  7],
       [10, 11]])

#### 15. Get the first column of the array above.

In [21]:
mat[:,0]

array([ 1,  5,  9, 13])

#### 16. Get the values in 2nd row for every 2 step.

In [22]:
mat[[1,1],[0,2]]

array([5, 7])

#### 17.Assign 77 to every cell in 3rd column.

In [23]:
mat[:,2]=77
mat

array([[ 1,  2, 77,  4],
       [ 5,  6, 77,  8],
       [ 9, 10, 77, 12],
       [13, 14, 77, 16]])

#### 18. Take 2nd row 1st column, 4th row 2nd column.

In [24]:
mat[[1,3],[0,1]]

array([ 5, 14])

#### 19. Take between 2nd and last row with step 2 and between 1st and last column with step 2.

In [25]:
mat[1::2, 0::2]

array([[ 5, 77],
       [13, 77]])

## NumPy Operations

#### 20. Get the sum of values smaller than 10 and values bigger than 12 from array above 

In [26]:
mat

array([[ 1,  2, 77,  4],
       [ 5,  6, 77,  8],
       [ 9, 10, 77, 12],
       [13, 14, 77, 16]])

In [27]:
mat[mat<10]

array([1, 2, 4, 5, 6, 8, 9])

In [28]:
mat[mat>12]

array([77, 77, 77, 13, 14, 77, 16])

In [29]:
mat[mat<10] + mat[mat>12]

array([78, 79, 81, 18, 20, 85, 25])

#### 21. Get the standard deviation of the result above

In [30]:
mat2=mat[mat<10]+mat[mat>12]
np.std(mat2,axis=0)

29.700546274093877

#### 22. Get the sum of the second column from array above

In [31]:
#print array here
mat

array([[ 1,  2, 77,  4],
       [ 5,  6, 77,  8],
       [ 9, 10, 77, 12],
       [13, 14, 77, 16]])

In [32]:
np.sum(mat[:,1])

32

#### 23. Get the median, mean and std of 3rd row from array above

In [33]:
mat[:,2]=[3,7,11,15]
mat

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [34]:
mat[2]

array([ 9, 10, 11, 12])

In [35]:
#median
np.median(mat[2])

10.5

In [36]:
#mean
np.mean(mat[2])

10.5

In [37]:
#std
np.std(mat[2])

1.118033988749895

# Pandas Section

In [38]:
import pandas as pd

**Read Salaries.csv and take a look at the first 5 rows, df info and df statistical measurements**

In [39]:
sal=pd.read_csv('Salaries.csv')

FileNotFoundError: ignored

In [ ]:
sal.head()

In [ ]:
sal.info()

In [ ]:
sal.describe()

**How many different year values are there?**

In [ ]:
sal.Year.value_counts()

**Print out max and avg Totalpay**

In [ ]:
#max
sal.TotalPay.max()


In [ ]:
#avg
sal.TotalPay.mean()

**How many records in the TotalPay column are there bigger than avg TotalPay**

In [ ]:
sal[ sal [ 'TotalPay' ] > sal[ 'TotalPay' ].mean() ].shape[0]

**How much does ALBERT PARDINI make (including benefits)?**

In [ ]:
sal[sal['EmployeeName']=='ALBERT PARDINI']['TotalPayBenefits']

**Who is the lowest paid person?**

In [ ]:
sal.head()

In [ ]:
sal[sal['TotalPay']==sal['TotalPay'].min()]

**What are the unique Jobs in dataset?**

In [ ]:
sal.JobTitle.unique()

**List 3 the least common Jobs**

In [ ]:
sal['JobTitle'].value_counts().tail(3)

**How many people earned more than avg in 2012?**

In [ ]:
sal[(sal['Year']==2012) & (sal['TotalPayBenefits']>sal['TotalPayBenefits'].mean())].shape[0]

**How many people have a title of Manager in their jobs?**

In [ ]:
#use apply function here
def finder(item):
    if 'MANAGER'.casefold() in item.casefold(): return True
    else: return False

In [ ]:
sal["JobTitle"][sal["JobTitle"].apply(finder)].size

**Take Id, EmployeeName, JobTitle, TotalPay and TotalPayBenefits columns with iloc and assign them as sal_new dataframe**

In [ ]:
sal_new= sal.iloc[:, [0,1,2,7,8]]
sal_new

In [ ]:
sal.head()

**Take the columns betweeen EmployeeName and TotalPayBenefits with loc and assign them as sal_new df** 

In [ ]:
sal_new=sal_new.loc[:, 'EmployeeName':'TotalPayBenefits']
sal_new

**Print out the names of the employees who earn more than min, but less than avg**

In [ ]:
sal[ (sal['TotalPayBenefits'].min() < sal['TotalPayBenefits']) & ( sal['TotalPayBenefits']  < sal['TotalPayBenefits'].mean()) ]["EmployeeName"]

___

<p style="text-align: center;"><img src="https://docs.google.com/uc?id=1lY0Uj5R04yMY3-ZppPWxqCr5pvBLYPnV" class="img-fluid" 
alt="CLRSWY"></p>

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#9d4f8c; font-size:100%; text-align:center; border-radius:10px 10px;">WAY TO REINVENT YOURSELF</p>

___